site_name: Kurs OI
repo_url: https://github.com/olimpiada/kurs-oi
repo_name: olimpiada/kurs-oi
edit_uri: edit/master/docs/

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - pymdownx.arithmatex:
      generic: true
  - md_in_html
  - mkdocs_graphviz

extra_javascript:
  - javascripts/mathjax.js
  - javascripts/preview-popup.js
  - https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdn.jsdelivr.net/gh/rod2ik/cdn@main/mkdocs/javascripts/mkdocs-graphviz.js

nav:
    - Start: 'index.md'
    - 'Początki programowania':
      - 'Pierwszy program w C++': './A-podstawy-programowania/A1-pierwszy-program.md'
      - 'Wczytywanie, wypisywanie, zmienne': './A-podstawy-programowania/A2-zmienne.md'
      - 'Technikalia, pierwsze zadania': './A-podstawy-programowania/A3-technikalia-zadania.md'
      - 'Instrukcja warunkowa (if)': './A-podstawy-programowania/A4-warunki.md'
      - 'Instrukcja przypisania i typ znakowy char': './A-podstawy-programowania/A5-przypisanie.md'
      - 'Pętla while': './A-podstawy-programowania/A6-while.md'
      - 'Pętla for i tablice': './A-podstawy-programowania/A7-for-tablice.md'
      - 'Funkcje': './A-podstawy-programowania/A8-funkcje.md'
#        - 'Więcej o pętlach i tablicach': './A-podstawy-programowania/Lekcja7.md'
#        - 'Efektywność programów': './A-podstawy-programowania/Lekcja9.md'
    - 'Podstawy algorytmiki':
      - 'Maksima i podciągi w tablicach': './B-proste-algorytmy/B1-podtablice.md'
      - 'Wyszukiwanie binarne, logarytm': './B-proste-algorytmy/B2-wyszukiwanie-binarne.md'
      - 'Złożoność obliczeniowa': './B-proste-algorytmy/B3-zlozonosc-1.md'
      - 'Systemy pozycyjne': './B-proste-algorytmy/B4-systemy-pozycyjne.md'
      - 'Rekurencja, szybkie potęgowanie i algorytm Euklidesa': './B-proste-algorytmy/B5-rekurencja.md'
      - 'Proste sortowanie': './B-proste-algorytmy/B6-sortowanie.md'
      - 'Sumy w tablicach': './B-proste-algorytmy/B7-sumy-gasienica.md'
    - 'Grafy':
      - 'DFS': './E-grafy/E2-dfs.md'
      - 'Sortowanie topologiczne': './E-grafy/E2-sortowanie-topologiczne.md'


extra_css:
  - stylesheets/extra.css

theme:
  favicon: assets/favicon.ico
  logo: assets/oi-logo-bg.png
  icon:
    repo: fontawesome/brands/github
  name: material
  language: pl
  features:
    - toc.integrate
    - content.action.edit
    - content.action.view
    # - navigation.sections
  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - primary: indigo
      accent: grey
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
