title: Stonks
memory_limit: 131072 # in kB
time_limit: 5000 # in milliseconds

scores:
    1 : 10
    2 : 30
    3 : 60

# See https://github.com/sio2project/sinol-make/blob/main/example_package/config.yml for more options
sinol_task_id: sto
sinol_contest_type: oi
sinol_expected_scores:
  max.cpp:
    expected:
      0: {points: 0, status: OK}
      1: {points: 10, status: OK}
      2: {points: 30, status: OK}
      3: {points: 60, status: OK}
    points: 100

sinol_static_tests: ["sto0.in"]